name: Organize Journal Files (Reusable)

on:
  workflow_call:
    inputs:
      image_tag:
        description: 'Docker image tag to use'
        required: false
        type: string
        default: 'latest'

jobs:
  organize-files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout journal repo
      uses: actions/checkout@v4
    
    
    - name: Run file organization
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/data \
          ghcr.io/${{ github.repository_owner }}/journal-organizer-workflow/journal-organizer:${{ inputs.image_tag }}
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action - Journal Organizer"
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "📁 Organize journal files - $(date '+%Y-%m-%d %H:%M:%S')"
          git push