name: Organize Journal Files (Reusable)

on:
  workflow_call:
    inputs:
      image_tag:
        description: 'Docker image tag to use'
        required: false
        type: string
        default: 'latest'
      commit_email:
        description: 'Email for git commits'
        required: false
        type: string
        default: 'action@github.com'
      commit_user:
        description: 'Name for git commits'
        required: false
        type: string
        default: 'GitHub Action - Journal Organizer'

jobs:
  organize-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout journal repo
      uses: actions/checkout@v4
    
    
    - name: Run file organization
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/data \
          ghcr.io/sofadb/inbox/journal-organizer:${{ inputs.image_tag }}
    
    - name: Commit and push changes
      run: |
        git config --local user.email "${{ inputs.commit_email }}"
        git config --local user.name "${{ inputs.commit_user }}"
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "📁 Organize journal files - $(date '+%Y-%m-%d %H:%M:%S')"
          git push
        fi