name: Organize Journal Files (Reusable)

on:
  workflow_call:
    inputs:
      inbox_repo:
        description: 'Inbox repository to clone (e.g., user/inbox)'
        required: true
        type: string
      inbox_path:
        description: 'Path to inbox files within the repo (/ or /inbox)'
        required: false
        type: string
        default: '/inbox'
      image_tag:
        description: 'Docker image tag to use'
        required: false
        type: string
        default: 'latest'
      commit_email:
        description: 'Email for git commits'
        required: false
        type: string
        default: 'action@github.com'
      commit_user:
        description: 'Name for git commits'
        required: false
        type: string
        default: 'GitHub Action - Journal Organizer'
    secrets:
      inbox_token:
        description: 'Token to access and clean the inbox repo'
        required: true

jobs:
  organize-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout journal repo
      uses: actions/checkout@v4
      with:
        token: ${{ github.token }}
        path: journal
    
    - name: Checkout inbox repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.inbox_repo }}
        token: ${{ secrets.inbox_token }}
        path: inbox
    
    - name: Copy inbox files to journal structure
      run: |
        echo "=== DEBUG: Setting up directories ==="
        mkdir -p journal/inbox
        
        echo "=== DEBUG: Listing workspace contents ==="
        ls -la ${{ github.workspace }}
        
        echo "=== DEBUG: Checking inbox repo contents ==="
        ls -la inbox/
        
        echo "=== DEBUG: Inbox path configuration ==="
        echo "inbox_path input: '${{ inputs.inbox_path }}'"
        
        if [ "${{ inputs.inbox_path }}" = "/" ]; then
          echo "=== DEBUG: Copying from root directory ==="
          echo "Files to copy:"
          ls -la inbox/*.md 2>/dev/null || echo "No .md files found in root"
          cp inbox/*.md journal/inbox/ 2>/dev/null || echo "No .md files found in root"
        else
          echo "=== DEBUG: Copying from subdirectory: inbox${{ inputs.inbox_path }} ==="
          echo "Directory contents:"
          ls -la inbox${{ inputs.inbox_path }}/ 2>/dev/null || echo "Directory does not exist"
          echo "Files to copy:"
          ls -la inbox${{ inputs.inbox_path }}/*.md 2>/dev/null || echo "No .md files found in ${{ inputs.inbox_path }}"
          cp inbox${{ inputs.inbox_path }}/*.md journal/inbox/ 2>/dev/null || echo "No .md files found in ${{ inputs.inbox_path }}"
        fi
        
        echo "=== DEBUG: Files copied to journal/inbox ==="
        ls -la journal/inbox/
    
    - name: Run file organization
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/journal:/data \
          ghcr.io/sofadb/inbox/journal-organizer:${{ inputs.image_tag }}
    
    - name: Clean inbox repo
      run: |
        cd inbox
        git config --local user.email "${{ inputs.commit_email }}"
        git config --local user.name "${{ inputs.commit_user }}"
        
        # Remove processed files from inbox directory only
        if [ "${{ inputs.inbox_path }}" = "/" ]; then
          rm -f *.md
        else
          rm -f .${{ inputs.inbox_path }}/*.md
        fi
        
        git add .
        if git diff --staged --quiet; then
          echo "No files to clean from inbox"
        else
          git commit -m "🧹 Clean processed journal files - $(date '+%Y-%m-%d %H:%M:%S')"
          git push
        fi
    
    - name: Commit and push journal changes
      run: |
        cd journal
        git config --local user.email "${{ inputs.commit_email }}"
        git config --local user.name "${{ inputs.commit_user }}"
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "📁 Organize journal files - $(date '+%Y-%m-%d %H:%M:%S')"
          git push
        fi
