name: Organize Journal Files (Reusable)

on:
  workflow_call:
    inputs:
      private_repo:
        description: 'Private repository to organize (format: owner/repo)'
        required: true
        type: string
      image_tag:
        description: 'Docker image tag to use'
        required: false
        type: string
        default: 'latest'
    secrets:
      private_repo_token:
        description: 'Personal Access Token for private repository'
        required: true

jobs:
  organize-files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout private journal repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.private_repo }}
        token: ${{ secrets.private_repo_token }}
        path: journal-repo
    
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Run file organization
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/journal-repo:/data \
          ghcr.io/${{ github.repository_owner }}/journal-organizer-workflow/journal-organizer:${{ inputs.image_tag }}
    
    - name: Commit and push changes to private repo
      run: |
        cd journal-repo
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action - Journal Organizer"
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "📁 Organize journal files - $(date '+%Y-%m-%d %H:%M:%S')"
          git push